### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by tonybrown85** [techslides/BackgroundProcess#1]
Hi Techslides,

I just wanted to get in touch to say a big thank you for demonstrating a simple example of the WP_Background_Process class! I was having a tough time implementing their example in the context of my plugin as only some elements of my plugin is OOP. I was able to get it working in 10 minutes after previously spending hours pulling my hair out with it. THANK YOU!

**Comment by techslides** [comment]
Thanks for the kind words. Happy it helped.
